---
- hosts: all
  sudo: no

####
  tasks:
  - name: Install dependencies
    apt:
        name={{ item }}
        update_cache=yes
    with_items:
        - python-dev
        - python-setuptools

  - name: Install pip
    easy_install:
        name=pip

  - name: Install docker-py
    pip:
        name=docker-py
        state=present
        version=1.1.0

#####
  - name: Add docker apt repo
    apt_repository:
        repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
        state=present

  - name: Import the Docker repository key
    apt_key:
        url=https://apt.dockerproject.org/gpg
        state=present
        id=2C52609D

  - name: Install Docker package
    apt:
        name=docker-engine
        update_cache=yes

####
  - name: application container
    docker:
      name: ruby-hw
      image: rstarmer/ruby-hw
      state: reloaded
      pull: always
      ports:
      - "80:80"
      - "22:2222"
